package com.lsfly.bas.model.system;

import java.io.Serializable;
import java.util.Date;

public class GenTableColumn implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.gen_table_id
     *
     * @mbg.generated
     */
    private String genTableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.table_name
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.column_length
     *
     * @mbg.generated
     */
    private Integer columnLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.show_name
     *
     * @mbg.generated
     */
    private String showName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.jdbc_type
     *
     * @mbg.generated
     */
    private String jdbcType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.java_type
     *
     * @mbg.generated
     */
    private String javaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.java_field
     *
     * @mbg.generated
     */
    private String javaField;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.is_pk
     *
     * @mbg.generated
     */
    private String isPk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.is_null
     *
     * @mbg.generated
     */
    private String isNull;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.is_query
     *
     * @mbg.generated
     */
    private String isQuery;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.query_type
     *
     * @mbg.generated
     */
    private String queryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.query_data
     *
     * @mbg.generated
     */
    private String queryData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.query_condition
     *
     * @mbg.generated
     */
    private String queryCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.is_list
     *
     * @mbg.generated
     */
    private String isList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.is_sort
     *
     * @mbg.generated
     */
    private String isSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.list_align
     *
     * @mbg.generated
     */
    private String listAlign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.list_field
     *
     * @mbg.generated
     */
    private String listField;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.is_edit
     *
     * @mbg.generated
     */
    private String isEdit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.edit_type
     *
     * @mbg.generated
     */
    private String editType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.edit_data
     *
     * @mbg.generated
     */
    private String editData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.is_required
     *
     * @mbg.generated
     */
    private String isRequired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.edit_verify
     *
     * @mbg.generated
     */
    private String editVerify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.sort
     *
     * @mbg.generated
     */
    private Long sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.field1
     *
     * @mbg.generated
     */
    private String field1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.field2
     *
     * @mbg.generated
     */
    private String field2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.field3
     *
     * @mbg.generated
     */
    private String field3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.field4
     *
     * @mbg.generated
     */
    private String field4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.field5
     *
     * @mbg.generated
     */
    private String field5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.is_delete_
     *
     * @mbg.generated
     */
    private String isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.version_
     *
     * @mbg.generated
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.create_by_
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.create_time_
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.update_by_
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table_column.update_time_
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gen_table_column
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.id
     *
     * @return the value of gen_table_column.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.id
     *
     * @param id the value for gen_table_column.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.gen_table_id
     *
     * @return the value of gen_table_column.gen_table_id
     *
     * @mbg.generated
     */
    public String getGenTableId() {
        return genTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.gen_table_id
     *
     * @param genTableId the value for gen_table_column.gen_table_id
     *
     * @mbg.generated
     */
    public void setGenTableId(String genTableId) {
        this.genTableId = genTableId == null ? null : genTableId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.table_name
     *
     * @return the value of gen_table_column.table_name
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.table_name
     *
     * @param tableName the value for gen_table_column.table_name
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.name
     *
     * @return the value of gen_table_column.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.name
     *
     * @param name the value for gen_table_column.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.column_length
     *
     * @return the value of gen_table_column.column_length
     *
     * @mbg.generated
     */
    public Integer getColumnLength() {
        return columnLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.column_length
     *
     * @param columnLength the value for gen_table_column.column_length
     *
     * @mbg.generated
     */
    public void setColumnLength(Integer columnLength) {
        this.columnLength = columnLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.show_name
     *
     * @return the value of gen_table_column.show_name
     *
     * @mbg.generated
     */
    public String getShowName() {
        return showName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.show_name
     *
     * @param showName the value for gen_table_column.show_name
     *
     * @mbg.generated
     */
    public void setShowName(String showName) {
        this.showName = showName == null ? null : showName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.comments
     *
     * @return the value of gen_table_column.comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.comments
     *
     * @param comments the value for gen_table_column.comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.jdbc_type
     *
     * @return the value of gen_table_column.jdbc_type
     *
     * @mbg.generated
     */
    public String getJdbcType() {
        return jdbcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.jdbc_type
     *
     * @param jdbcType the value for gen_table_column.jdbc_type
     *
     * @mbg.generated
     */
    public void setJdbcType(String jdbcType) {
        this.jdbcType = jdbcType == null ? null : jdbcType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.java_type
     *
     * @return the value of gen_table_column.java_type
     *
     * @mbg.generated
     */
    public String getJavaType() {
        return javaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.java_type
     *
     * @param javaType the value for gen_table_column.java_type
     *
     * @mbg.generated
     */
    public void setJavaType(String javaType) {
        this.javaType = javaType == null ? null : javaType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.java_field
     *
     * @return the value of gen_table_column.java_field
     *
     * @mbg.generated
     */
    public String getJavaField() {
        return javaField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.java_field
     *
     * @param javaField the value for gen_table_column.java_field
     *
     * @mbg.generated
     */
    public void setJavaField(String javaField) {
        this.javaField = javaField == null ? null : javaField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.is_pk
     *
     * @return the value of gen_table_column.is_pk
     *
     * @mbg.generated
     */
    public String getIsPk() {
        return isPk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.is_pk
     *
     * @param isPk the value for gen_table_column.is_pk
     *
     * @mbg.generated
     */
    public void setIsPk(String isPk) {
        this.isPk = isPk == null ? null : isPk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.is_null
     *
     * @return the value of gen_table_column.is_null
     *
     * @mbg.generated
     */
    public String getIsNull() {
        return isNull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.is_null
     *
     * @param isNull the value for gen_table_column.is_null
     *
     * @mbg.generated
     */
    public void setIsNull(String isNull) {
        this.isNull = isNull == null ? null : isNull.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.is_query
     *
     * @return the value of gen_table_column.is_query
     *
     * @mbg.generated
     */
    public String getIsQuery() {
        return isQuery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.is_query
     *
     * @param isQuery the value for gen_table_column.is_query
     *
     * @mbg.generated
     */
    public void setIsQuery(String isQuery) {
        this.isQuery = isQuery == null ? null : isQuery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.query_type
     *
     * @return the value of gen_table_column.query_type
     *
     * @mbg.generated
     */
    public String getQueryType() {
        return queryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.query_type
     *
     * @param queryType the value for gen_table_column.query_type
     *
     * @mbg.generated
     */
    public void setQueryType(String queryType) {
        this.queryType = queryType == null ? null : queryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.query_data
     *
     * @return the value of gen_table_column.query_data
     *
     * @mbg.generated
     */
    public String getQueryData() {
        return queryData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.query_data
     *
     * @param queryData the value for gen_table_column.query_data
     *
     * @mbg.generated
     */
    public void setQueryData(String queryData) {
        this.queryData = queryData == null ? null : queryData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.query_condition
     *
     * @return the value of gen_table_column.query_condition
     *
     * @mbg.generated
     */
    public String getQueryCondition() {
        return queryCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.query_condition
     *
     * @param queryCondition the value for gen_table_column.query_condition
     *
     * @mbg.generated
     */
    public void setQueryCondition(String queryCondition) {
        this.queryCondition = queryCondition == null ? null : queryCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.is_list
     *
     * @return the value of gen_table_column.is_list
     *
     * @mbg.generated
     */
    public String getIsList() {
        return isList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.is_list
     *
     * @param isList the value for gen_table_column.is_list
     *
     * @mbg.generated
     */
    public void setIsList(String isList) {
        this.isList = isList == null ? null : isList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.is_sort
     *
     * @return the value of gen_table_column.is_sort
     *
     * @mbg.generated
     */
    public String getIsSort() {
        return isSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.is_sort
     *
     * @param isSort the value for gen_table_column.is_sort
     *
     * @mbg.generated
     */
    public void setIsSort(String isSort) {
        this.isSort = isSort == null ? null : isSort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.list_align
     *
     * @return the value of gen_table_column.list_align
     *
     * @mbg.generated
     */
    public String getListAlign() {
        return listAlign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.list_align
     *
     * @param listAlign the value for gen_table_column.list_align
     *
     * @mbg.generated
     */
    public void setListAlign(String listAlign) {
        this.listAlign = listAlign == null ? null : listAlign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.list_field
     *
     * @return the value of gen_table_column.list_field
     *
     * @mbg.generated
     */
    public String getListField() {
        return listField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.list_field
     *
     * @param listField the value for gen_table_column.list_field
     *
     * @mbg.generated
     */
    public void setListField(String listField) {
        this.listField = listField == null ? null : listField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.is_edit
     *
     * @return the value of gen_table_column.is_edit
     *
     * @mbg.generated
     */
    public String getIsEdit() {
        return isEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.is_edit
     *
     * @param isEdit the value for gen_table_column.is_edit
     *
     * @mbg.generated
     */
    public void setIsEdit(String isEdit) {
        this.isEdit = isEdit == null ? null : isEdit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.edit_type
     *
     * @return the value of gen_table_column.edit_type
     *
     * @mbg.generated
     */
    public String getEditType() {
        return editType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.edit_type
     *
     * @param editType the value for gen_table_column.edit_type
     *
     * @mbg.generated
     */
    public void setEditType(String editType) {
        this.editType = editType == null ? null : editType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.edit_data
     *
     * @return the value of gen_table_column.edit_data
     *
     * @mbg.generated
     */
    public String getEditData() {
        return editData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.edit_data
     *
     * @param editData the value for gen_table_column.edit_data
     *
     * @mbg.generated
     */
    public void setEditData(String editData) {
        this.editData = editData == null ? null : editData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.is_required
     *
     * @return the value of gen_table_column.is_required
     *
     * @mbg.generated
     */
    public String getIsRequired() {
        return isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.is_required
     *
     * @param isRequired the value for gen_table_column.is_required
     *
     * @mbg.generated
     */
    public void setIsRequired(String isRequired) {
        this.isRequired = isRequired == null ? null : isRequired.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.edit_verify
     *
     * @return the value of gen_table_column.edit_verify
     *
     * @mbg.generated
     */
    public String getEditVerify() {
        return editVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.edit_verify
     *
     * @param editVerify the value for gen_table_column.edit_verify
     *
     * @mbg.generated
     */
    public void setEditVerify(String editVerify) {
        this.editVerify = editVerify == null ? null : editVerify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.sort
     *
     * @return the value of gen_table_column.sort
     *
     * @mbg.generated
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.sort
     *
     * @param sort the value for gen_table_column.sort
     *
     * @mbg.generated
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.field1
     *
     * @return the value of gen_table_column.field1
     *
     * @mbg.generated
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.field1
     *
     * @param field1 the value for gen_table_column.field1
     *
     * @mbg.generated
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.field2
     *
     * @return the value of gen_table_column.field2
     *
     * @mbg.generated
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.field2
     *
     * @param field2 the value for gen_table_column.field2
     *
     * @mbg.generated
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.field3
     *
     * @return the value of gen_table_column.field3
     *
     * @mbg.generated
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.field3
     *
     * @param field3 the value for gen_table_column.field3
     *
     * @mbg.generated
     */
    public void setField3(String field3) {
        this.field3 = field3 == null ? null : field3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.field4
     *
     * @return the value of gen_table_column.field4
     *
     * @mbg.generated
     */
    public String getField4() {
        return field4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.field4
     *
     * @param field4 the value for gen_table_column.field4
     *
     * @mbg.generated
     */
    public void setField4(String field4) {
        this.field4 = field4 == null ? null : field4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.field5
     *
     * @return the value of gen_table_column.field5
     *
     * @mbg.generated
     */
    public String getField5() {
        return field5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.field5
     *
     * @param field5 the value for gen_table_column.field5
     *
     * @mbg.generated
     */
    public void setField5(String field5) {
        this.field5 = field5 == null ? null : field5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.is_delete_
     *
     * @return the value of gen_table_column.is_delete_
     *
     * @mbg.generated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.is_delete_
     *
     * @param isDelete the value for gen_table_column.is_delete_
     *
     * @mbg.generated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.version_
     *
     * @return the value of gen_table_column.version_
     *
     * @mbg.generated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.version_
     *
     * @param version the value for gen_table_column.version_
     *
     * @mbg.generated
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.create_by_
     *
     * @return the value of gen_table_column.create_by_
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.create_by_
     *
     * @param createBy the value for gen_table_column.create_by_
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.create_time_
     *
     * @return the value of gen_table_column.create_time_
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.create_time_
     *
     * @param createTime the value for gen_table_column.create_time_
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.update_by_
     *
     * @return the value of gen_table_column.update_by_
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.update_by_
     *
     * @param updateBy the value for gen_table_column.update_by_
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table_column.update_time_
     *
     * @return the value of gen_table_column.update_time_
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table_column.update_time_
     *
     * @param updateTime the value for gen_table_column.update_time_
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_column
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", genTableId=").append(genTableId);
        sb.append(", tableName=").append(tableName);
        sb.append(", name=").append(name);
        sb.append(", columnLength=").append(columnLength);
        sb.append(", showName=").append(showName);
        sb.append(", comments=").append(comments);
        sb.append(", jdbcType=").append(jdbcType);
        sb.append(", javaType=").append(javaType);
        sb.append(", javaField=").append(javaField);
        sb.append(", isPk=").append(isPk);
        sb.append(", isNull=").append(isNull);
        sb.append(", isQuery=").append(isQuery);
        sb.append(", queryType=").append(queryType);
        sb.append(", queryData=").append(queryData);
        sb.append(", queryCondition=").append(queryCondition);
        sb.append(", isList=").append(isList);
        sb.append(", isSort=").append(isSort);
        sb.append(", listAlign=").append(listAlign);
        sb.append(", listField=").append(listField);
        sb.append(", isEdit=").append(isEdit);
        sb.append(", editType=").append(editType);
        sb.append(", editData=").append(editData);
        sb.append(", isRequired=").append(isRequired);
        sb.append(", editVerify=").append(editVerify);
        sb.append(", sort=").append(sort);
        sb.append(", field1=").append(field1);
        sb.append(", field2=").append(field2);
        sb.append(", field3=").append(field3);
        sb.append(", field4=").append(field4);
        sb.append(", field5=").append(field5);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", version=").append(version);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_column
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GenTableColumn other = (GenTableColumn) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGenTableId() == null ? other.getGenTableId() == null : this.getGenTableId().equals(other.getGenTableId()))
            && (this.getTableName() == null ? other.getTableName() == null : this.getTableName().equals(other.getTableName()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getColumnLength() == null ? other.getColumnLength() == null : this.getColumnLength().equals(other.getColumnLength()))
            && (this.getShowName() == null ? other.getShowName() == null : this.getShowName().equals(other.getShowName()))
            && (this.getComments() == null ? other.getComments() == null : this.getComments().equals(other.getComments()))
            && (this.getJdbcType() == null ? other.getJdbcType() == null : this.getJdbcType().equals(other.getJdbcType()))
            && (this.getJavaType() == null ? other.getJavaType() == null : this.getJavaType().equals(other.getJavaType()))
            && (this.getJavaField() == null ? other.getJavaField() == null : this.getJavaField().equals(other.getJavaField()))
            && (this.getIsPk() == null ? other.getIsPk() == null : this.getIsPk().equals(other.getIsPk()))
            && (this.getIsNull() == null ? other.getIsNull() == null : this.getIsNull().equals(other.getIsNull()))
            && (this.getIsQuery() == null ? other.getIsQuery() == null : this.getIsQuery().equals(other.getIsQuery()))
            && (this.getQueryType() == null ? other.getQueryType() == null : this.getQueryType().equals(other.getQueryType()))
            && (this.getQueryData() == null ? other.getQueryData() == null : this.getQueryData().equals(other.getQueryData()))
            && (this.getQueryCondition() == null ? other.getQueryCondition() == null : this.getQueryCondition().equals(other.getQueryCondition()))
            && (this.getIsList() == null ? other.getIsList() == null : this.getIsList().equals(other.getIsList()))
            && (this.getIsSort() == null ? other.getIsSort() == null : this.getIsSort().equals(other.getIsSort()))
            && (this.getListAlign() == null ? other.getListAlign() == null : this.getListAlign().equals(other.getListAlign()))
            && (this.getListField() == null ? other.getListField() == null : this.getListField().equals(other.getListField()))
            && (this.getIsEdit() == null ? other.getIsEdit() == null : this.getIsEdit().equals(other.getIsEdit()))
            && (this.getEditType() == null ? other.getEditType() == null : this.getEditType().equals(other.getEditType()))
            && (this.getEditData() == null ? other.getEditData() == null : this.getEditData().equals(other.getEditData()))
            && (this.getIsRequired() == null ? other.getIsRequired() == null : this.getIsRequired().equals(other.getIsRequired()))
            && (this.getEditVerify() == null ? other.getEditVerify() == null : this.getEditVerify().equals(other.getEditVerify()))
            && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
            && (this.getField1() == null ? other.getField1() == null : this.getField1().equals(other.getField1()))
            && (this.getField2() == null ? other.getField2() == null : this.getField2().equals(other.getField2()))
            && (this.getField3() == null ? other.getField3() == null : this.getField3().equals(other.getField3()))
            && (this.getField4() == null ? other.getField4() == null : this.getField4().equals(other.getField4()))
            && (this.getField5() == null ? other.getField5() == null : this.getField5().equals(other.getField5()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_column
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGenTableId() == null) ? 0 : getGenTableId().hashCode());
        result = prime * result + ((getTableName() == null) ? 0 : getTableName().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getColumnLength() == null) ? 0 : getColumnLength().hashCode());
        result = prime * result + ((getShowName() == null) ? 0 : getShowName().hashCode());
        result = prime * result + ((getComments() == null) ? 0 : getComments().hashCode());
        result = prime * result + ((getJdbcType() == null) ? 0 : getJdbcType().hashCode());
        result = prime * result + ((getJavaType() == null) ? 0 : getJavaType().hashCode());
        result = prime * result + ((getJavaField() == null) ? 0 : getJavaField().hashCode());
        result = prime * result + ((getIsPk() == null) ? 0 : getIsPk().hashCode());
        result = prime * result + ((getIsNull() == null) ? 0 : getIsNull().hashCode());
        result = prime * result + ((getIsQuery() == null) ? 0 : getIsQuery().hashCode());
        result = prime * result + ((getQueryType() == null) ? 0 : getQueryType().hashCode());
        result = prime * result + ((getQueryData() == null) ? 0 : getQueryData().hashCode());
        result = prime * result + ((getQueryCondition() == null) ? 0 : getQueryCondition().hashCode());
        result = prime * result + ((getIsList() == null) ? 0 : getIsList().hashCode());
        result = prime * result + ((getIsSort() == null) ? 0 : getIsSort().hashCode());
        result = prime * result + ((getListAlign() == null) ? 0 : getListAlign().hashCode());
        result = prime * result + ((getListField() == null) ? 0 : getListField().hashCode());
        result = prime * result + ((getIsEdit() == null) ? 0 : getIsEdit().hashCode());
        result = prime * result + ((getEditType() == null) ? 0 : getEditType().hashCode());
        result = prime * result + ((getEditData() == null) ? 0 : getEditData().hashCode());
        result = prime * result + ((getIsRequired() == null) ? 0 : getIsRequired().hashCode());
        result = prime * result + ((getEditVerify() == null) ? 0 : getEditVerify().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getField1() == null) ? 0 : getField1().hashCode());
        result = prime * result + ((getField2() == null) ? 0 : getField2().hashCode());
        result = prime * result + ((getField3() == null) ? 0 : getField3().hashCode());
        result = prime * result + ((getField4() == null) ? 0 : getField4().hashCode());
        result = prime * result + ((getField5() == null) ? 0 : getField5().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}