package com.lsfly.bas.dao.video;

import com.lsfly.bas.model.video.TVideo;
import com.lsfly.bas.model.video.TVideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_
     *
     * @mbg.generated
     */
    long countByExample(TVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_
     *
     * @mbg.generated
     */
    int deleteByExample(TVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_
     *
     * @mbg.generated
     */
    int insert(TVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_
     *
     * @mbg.generated
     */
    int insertSelective(TVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_
     *
     * @mbg.generated
     */
    List<TVideo> selectByExampleWithRowbounds(TVideoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_
     *
     * @mbg.generated
     */
    List<TVideo> selectByExample(TVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_
     *
     * @mbg.generated
     */
    TVideo selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TVideo record, @Param("example") TVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TVideo record, @Param("example") TVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video_
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TVideo record);
}