package com.lsfly.bas.dao.courseUser;

import com.lsfly.bas.model.courseUser.TCourseUser;
import com.lsfly.bas.model.courseUser.TCourseUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TCourseUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_
     *
     * @mbg.generated
     */
    long countByExample(TCourseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_
     *
     * @mbg.generated
     */
    int deleteByExample(TCourseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_
     *
     * @mbg.generated
     */
    int insert(TCourseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_
     *
     * @mbg.generated
     */
    int insertSelective(TCourseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_
     *
     * @mbg.generated
     */
    List<TCourseUser> selectByExampleWithRowbounds(TCourseUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_
     *
     * @mbg.generated
     */
    List<TCourseUser> selectByExample(TCourseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_
     *
     * @mbg.generated
     */
    TCourseUser selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCourseUser record, @Param("example") TCourseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCourseUser record, @Param("example") TCourseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCourseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCourseUser record);
}