package com.lsfly.bas.dao.courseUser;

import com.lsfly.bas.model.courseUser.TCourseUserVideo;
import com.lsfly.bas.model.courseUser.TCourseUserVideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TCourseUserVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_video_
     *
     * @mbg.generated
     */
    long countByExample(TCourseUserVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_video_
     *
     * @mbg.generated
     */
    int deleteByExample(TCourseUserVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_video_
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_video_
     *
     * @mbg.generated
     */
    int insert(TCourseUserVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_video_
     *
     * @mbg.generated
     */
    int insertSelective(TCourseUserVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_video_
     *
     * @mbg.generated
     */
    List<TCourseUserVideo> selectByExampleWithRowbounds(TCourseUserVideoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_video_
     *
     * @mbg.generated
     */
    List<TCourseUserVideo> selectByExample(TCourseUserVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_video_
     *
     * @mbg.generated
     */
    TCourseUserVideo selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_video_
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCourseUserVideo record, @Param("example") TCourseUserVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_video_
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCourseUserVideo record, @Param("example") TCourseUserVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_video_
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCourseUserVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_user_video_
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCourseUserVideo record);
}