package com.lsfly.bas.dao.course;

import com.lsfly.bas.model.course.TCourseVideo;
import com.lsfly.bas.model.course.TCourseVideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TCourseVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video_
     *
     * @mbg.generated
     */
    long countByExample(TCourseVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video_
     *
     * @mbg.generated
     */
    int deleteByExample(TCourseVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video_
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video_
     *
     * @mbg.generated
     */
    int insert(TCourseVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video_
     *
     * @mbg.generated
     */
    int insertSelective(TCourseVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video_
     *
     * @mbg.generated
     */
    List<TCourseVideo> selectByExampleWithRowbounds(TCourseVideoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video_
     *
     * @mbg.generated
     */
    List<TCourseVideo> selectByExample(TCourseVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video_
     *
     * @mbg.generated
     */
    TCourseVideo selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video_
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCourseVideo record, @Param("example") TCourseVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video_
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCourseVideo record, @Param("example") TCourseVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video_
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCourseVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video_
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCourseVideo record);
}