package com.lsfly.bas.dao.course;

import com.lsfly.bas.model.course.TCourse;
import com.lsfly.bas.model.course.TCourseExample;
import com.lsfly.bas.model.course.TCourseWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_
     *
     * @mbg.generated
     */
    long countByExample(TCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_
     *
     * @mbg.generated
     */
    int deleteByExample(TCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_
     *
     * @mbg.generated
     */
    int insert(TCourseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_
     *
     * @mbg.generated
     */
    int insertSelective(TCourseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_
     *
     * @mbg.generated
     */
    List<TCourseWithBLOBs> selectByExampleWithBLOBsWithRowbounds(TCourseExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_
     *
     * @mbg.generated
     */
    List<TCourseWithBLOBs> selectByExampleWithBLOBs(TCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_
     *
     * @mbg.generated
     */
    List<TCourse> selectByExampleWithRowbounds(TCourseExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_
     *
     * @mbg.generated
     */
    List<TCourse> selectByExample(TCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_
     *
     * @mbg.generated
     */
    TCourseWithBLOBs selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCourseWithBLOBs record, @Param("example") TCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TCourseWithBLOBs record, @Param("example") TCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCourse record, @Param("example") TCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCourseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TCourseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCourse record);
}