package com.lsfly.bas.dao.system;


import com.lsfly.bas.model.system.GenTableColumn;
import com.lsfly.bas.model.system.GenTableColumnExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface GenTableColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_column
     *
     * @mbg.generated
     */
    long countByExample(GenTableColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_column
     *
     * @mbg.generated
     */
    int deleteByExample(GenTableColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_column
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_column
     *
     * @mbg.generated
     */
    int insert(GenTableColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_column
     *
     * @mbg.generated
     */
    int insertSelective(GenTableColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_column
     *
     * @mbg.generated
     */
    List<GenTableColumn> selectByExampleWithRowbounds(GenTableColumnExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_column
     *
     * @mbg.generated
     */
    List<GenTableColumn> selectByExample(GenTableColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_column
     *
     * @mbg.generated
     */
    GenTableColumn selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_column
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GenTableColumn record, @Param("example") GenTableColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_column
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GenTableColumn record, @Param("example") GenTableColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_column
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GenTableColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_column
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GenTableColumn record);
}