package com.lsfly.bas.dao.system;


import com.lsfly.bas.model.system.GenTableTree;
import com.lsfly.bas.model.system.GenTableTreeExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface GenTableTreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_tree
     *
     * @mbg.generated
     */
    long countByExample(GenTableTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_tree
     *
     * @mbg.generated
     */
    int deleteByExample(GenTableTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_tree
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_tree
     *
     * @mbg.generated
     */
    int insert(GenTableTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_tree
     *
     * @mbg.generated
     */
    int insertSelective(GenTableTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_tree
     *
     * @mbg.generated
     */
    List<GenTableTree> selectByExampleWithRowbounds(GenTableTreeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_tree
     *
     * @mbg.generated
     */
    List<GenTableTree> selectByExample(GenTableTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_tree
     *
     * @mbg.generated
     */
    GenTableTree selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_tree
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GenTableTree record, @Param("example") GenTableTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_tree
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GenTableTree record, @Param("example") GenTableTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_tree
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GenTableTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table_tree
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GenTableTree record);
}