package com.lsfly.bas.dao.system;

import com.lsfly.bas.model.system.SysKey;
import com.lsfly.bas.model.system.SysKeyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbg.generated
     */
    long countByExample(SysKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbg.generated
     */
    int deleteByExample(SysKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbg.generated
     */
    int insert(SysKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbg.generated
     */
    int insertSelective(SysKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbg.generated
     */
    List<SysKey> selectByExampleWithRowbounds(SysKeyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbg.generated
     */
    List<SysKey> selectByExample(SysKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbg.generated
     */
    SysKey selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysKey record, @Param("example") SysKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysKey record, @Param("example") SysKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysKey record);
}