package com.lsfly.bas.dao.system;

import com.lsfly.bas.model.system.SysRoleKey;
import com.lsfly.bas.model.system.SysRoleKeyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysRoleKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_key
     *
     * @mbg.generated
     */
    long countByExample(SysRoleKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_key
     *
     * @mbg.generated
     */
    int deleteByExample(SysRoleKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_key
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_key
     *
     * @mbg.generated
     */
    int insert(SysRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_key
     *
     * @mbg.generated
     */
    int insertSelective(SysRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_key
     *
     * @mbg.generated
     */
    List<SysRoleKey> selectByExampleWithRowbounds(SysRoleKeyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_key
     *
     * @mbg.generated
     */
    List<SysRoleKey> selectByExample(SysRoleKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_key
     *
     * @mbg.generated
     */
    SysRoleKey selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_key
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysRoleKey record, @Param("example") SysRoleKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_key
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysRoleKey record, @Param("example") SysRoleKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysRoleKey record);
}